applications/persona/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "persona_app"

urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'),
    path('listar-todo-empleados', views.ListAllEmpleados.as_view(), name='empleados_all'),
    path('listar-empleados-admin', views.ListaEmpleadosAdmin.as_view(), name='empleados_admin'),
    path('lista-by-area/<shorname>/', views.ListByAreaEmpleado.as_view(), name='empleados_area'),
    path('buscar-empleado', views.ListEmpleadosByKword.as_view()),
    path('listar-habilidades-empleado', views.ListHabilidadesHempleados.as_view()),
    path('ver-empleado/<pk>/', views.EmpleadoDetailView.as_view(), name='Empleado_Detail'),
    path('add-empleado', views.EmpleadoCreateView.as_view(), name='empleado_add'),
    path('success', views.SuccessView.as_view(), name='correcto'),
    path('update-empleado/<pk>/', views.EmpleadoUpDateView.as_view(), name='modificar_empleado'),
    path('delete-empleado/<pk>/', views.EmpleadoDeleteView.as_view(), name='eliminar_empleado'),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.departamento.urls')),
    re_path('', include('applications.persona.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.persona.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/persona/models.py
from re import T
from django.db import models
#
from applications.departamento.models import Departamento

from ckeditor.fields import RichTextField

class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)
    
    class meta:
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidads Empleados'
        
    def __str__(self):
        return str(self.id) + '-' + self.habilidad
    
    
    
    
# Create your models here.
class Empleado(models.Model):
    """Modelo para tabla empleado"""
    
    JOB_CHOICES = (
        ('0', 'CONTADOR'),
        ('1', 'ADMINISTRADOR'),
        ('2', 'ECONOMISTA'),
        ('3', 'OTRO'),
    )
    first_name = models.CharField('Nombres', max_length=60)
    last_name = models.CharField('Apellidos', max_length=60)
    full_name = models.CharField(
        'Nombres completos',
        max_length=120,
        blank=True
    )
    job = models.CharField('trabajo', max_length=1, choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE) #asi se crea la relacion entre :
    #persona y departamento(que es lo que se solicita)
    avatar = models.ImageField(upload_to='empleado', blank=True, null=True)
    Habilidades = models.ManyToManyField(Habilidades)
    hola_vida = RichTextField()

    class Meta:
        verbose_name = 'Mi Persona'
        verbose_name_plural = 'Registo de Persona'
        ordering = ['first_name']
        unique_together = ('first_name', 'last_name')

    def __str__(self):
        return str(self.id) + '-' + self.first_name + '-' + self.last_name

applications/persona/forms.py
from django import forms

from .models import Empleado

class EmpleadoForm(forms.ModelForm):
    
    class Meta:
        model = Empleado
        fields = (
            'first_name',
            'last_name',
            'job',
            'departamento',
            'avatar',
            'Habilidades',
        )
        widgets = {
            'Habilidades': forms.CheckboxSelectMultiple()
        }

applications/persona/views.py
from multiprocessing import context
from django.shortcuts import render
from django.urls import reverse_lazy
from django.test import LiveServerTestCase
from django.views.generic import ( 
    ListView, 
    DetailView,
    CreateView,
    TemplateView,
    UpdateView,
    DeleteView,
    
)
#models
from .models import Empleado
#forms
from .forms import EmpleadoForm

class InicioView(TemplateView):
    """vista que carga la pag de nicio"""
    template_name = 'inicio.html'
    

class ListAllEmpleados(ListView):
    template_name = 'persona/list_all.html'
    paginate_by = 4
    ordering = 'first_name'
    context_object_name = 'empleados'
    
    def get_queryset(self):
        print('************')
        palabra_clave = self.request.GET.get("kword", '')
        lista = Empleado.objects.filter(
            full_name__icontains=palabra_clave
        )
        return lista
    
class ListaEmpleadosAdmin(ListView):
    template_name = 'persona/lista_empleados.html'
    paginate_by = 4
    ordering = 'first_name'
    context_object_name = 'empleados'
    model = Empleado

class ListByAreaEmpleado(ListView):
    """ lista empleados de un area """
    template_name = 'persona/list_by_area.html'
    context_object_name = 'empleados'
    
    def get_queryset(self):
        area = self.kwargs['shorname']
        lista = Empleado.objects.filter(
        departamento__shor_name=area
        )
        return lista 

#vista sobre buscador    
class ListEmpleadosByKword(ListView):
    """ lista empleado por palabra clave """
    template_name = 'persona/by_kword.html'
    context_object_name = 'empleados'
    
    def get_queryset(self):
        print('************')
        palabra_clave = self.request.GET.get("kword", '')
        lista = Empleado.objects.filter(
            first_name= palabra_clave
        )
        return lista
    
class ListHabilidadesHempleados(ListView):
    template_name = 'persona/habilidades.html'
    paginate_by = 4
    context_object_name = 'habilidades'
    
    def get_queryset(self):
        empleado = Empleado.objects.get(id=3)
        return empleado.Habilidades.all()
    
class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = "persona/detailempleado.html"
    
    def get_context_data(self, **kwargs):
        context = super(EmpleadoDetailView, self).get_context_data(**kwargs)
        context['titulo'] = 'informacion del empleado'
        return context




class SuccessView(TemplateView):
    template_name = "persona/success.html"


class EmpleadoCreateView(CreateView):
    template_name = "persona/add.html"
    model = Empleado
    form_class = EmpleadoForm
    success_url = reverse_lazy('persona_app:empleados_admin')
    
    def form_valid(self, form):
        empleado = form.save(commit=False)
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)
    
    
    
    
    
class EmpleadoUpDateView(UpdateView):
    template_name = "persona/update.html"
    model = Empleado
    fields = [
        'first_name',
        'last_name',
        'job',
        'departamento',
        'Habilidades',
    ]
    success_url = reverse_lazy('persona_app:empleados_admin')
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        print('*****metodo post*****')
        print('======')
        print(request.POST)
        print(request.POST['last_name'])
        return super().post(request, *args, **kwargs)
    
    def form_valid(self, form):
        print('****metodo form_valid******')
        print('**********')
        return super(EmpleadoUpDateView, self).form_valid(form)
    
class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = "persona/delete.html"
    success_url = reverse_lazy('persona_app:empleados_admin')

templates/persona/add.html
{% extends 'base.html' %}

{% block title %}
   Registrar Empleado
{% endblock title %}

{% block content %}
   
{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar empleado</h1>
        <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}

            <div class="medium-6 cell">
                <label>Nombres:
                  {{form.first_name}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Apellidos:
                  {{form.last_name}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Trabajo:
                  {{form.job}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Departamento:
                  {{form.departamento}}
                </label>
            </div>
            <div class="medium-6 cell">
              <label>Habilidades:
                {{form.Habilidades}}
              </label>
          </div>
            <div class="medium-6 cell">
              <label>Foto:
                {{form.avatar}}
              </label>
          </div>
            <div class="medium-6 cell">
                <button type="submit" class="button success">Guardar</button>
            </div>
        </form>
    </div>
</div>

{% endblock content %}

templates/persona/by_kword.html
<h1> buscar empleados por palabra clave </h1>
<form method = "GET">{% csrf_token %}
    <input type="text" id="kword" name="kword" placeholder="ingrese nombre aqui">
    <button type="submit">Buscar</button>
</form>

<h3>lista resultados</h1>
<ul>
    {% for e in empleados %}
       <li>{{e}}</li>   
    {% endfor %}
</ul

templates/persona/delete.html
{% extends 'base.html' %}

{% block title %}
    Eliminar empleado
{% endblock title %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Eliminar empleado: {{ object.full_name }}</h1>

        <form class="cell" method="POST">{% csrf_token %}
            
            <div class="callout secondary">
                <h5>¿Desea eliminar este Empleado?</h5>
                <button type="submit" class="alert button">confirmar</button>
            </div>
        </form>
    </div>
</div>

{% endblock content %}

templates/persona/detailempleado.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
   {{ object.full_name }}
{% endblock title %}

{% block content %}
   
{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x grid-margin-x align-center">
        <div class="cell  large-4 card" style="width: 300px; margin-top: 10px;">
            <div class="card-divider">
              {{ empleado.get_job_display }}
            </div>
            {% if empleado.avatar %}
              <img src="{{ empleado.avatar.url }}">
            {% else %}
              <img src="{% static 'img/ep.jpg' %}">
            {% endif %}

            <div class="card-section">
              <h4>{{ empleado.full_name }}</h4>
              <p>{{ empleado.last_name }}</p>
              <p>{{ empleado.departamento.shor_name }}</p>
              <p><span class="label">Habilidades:</span></p>
              <ul class="vertical menu">
                {% for h in empleado.Habilidades.all %}
                  <li>{{ h.habilidad }}</li>
                {% endfor %}
              </ul>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/persona/habilidades.html
<h1>habilidades de un empleado</h1>
<ul>
    {% for h in habilidades %}
        <li> {{h}} </li>
    {% endfor %}
</ul>

templates/persona/list_all.html
<h1>lista de todos los empleados</h1>
<ul>
    {% for e in object_list %}
        <li>{{ e }}</li>
    {% endfor %}

</ul>

templates/persona/list_by_area.html
{% extends 'base.html' %}

{% block title%}
   Lista empleados por departamentos
{% endblock title %}

{% block content %}
  {% include "includes/header.html" %}

 <div class="grid-container">
    <div class="grid-x">
      <div class="cell">Empleado por area:</div>
      <div class="cell">
        <table>
            <thead>
              <tr>
                  <th width="200">ID</th>
                  <th>NOMBRES</th>
                  <th width="150">APELLIDOS</th>
                  <th width="150">DEPARTAMENTOS</th>
                  <th width="150">ACCION</th>
              </tr>
            </thead>
            <tbody>
              {% for e in empleados %}
              <tr>
                  <td>{{ e.id }}</td>
                  <td>{{ e.first_name }}</td>
                  <td>{{ e.last_name }}</td>
                  <td>{{ e.departamento }}</td>
                  <td><a class="button warning" href="{% url 'persona_app:Empleado_Detail' e.id  %}">Ver</a></td>
              </tr>
              {% endfor %}
            </tbody>
        </table>
      </div>
    </div> 
 </div>



{% endblock content %}


<h1>Lista empleados por departamentos</h1>

<ul>
    {%for e in object_list %}
      <li> {{ e }} </li>
    {% endfor %}

templates/persona/lista_empleados.html
{%extends 'base.html'%}

{% block content %}
{% include "includes/header.html" %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">lista Empleados</h1>
        <div class="cell">
            <table>
                <thead>
                  <tr>
                     <th width="200">ID</th>
                     <th>NOMBRES</th>
                     <th width="150">APELLIDOS</th>
                     <th width="150">DEPARTAMENTOS</th>
                     <th width="150">ACCION</th>
                  </tr>
                </thead>
                <tbody>
                    {% for e in empleados %}
                    <tr>
                         <td>{{ e.id }}</td>
                         <td>{{ e.first_name }}</td>
                         <td>{{ e.last_name }}</td>
                         <td>{{ e.departamento }}</td>
                         <td>
                            <a class="button success" href="{% url 'persona_app:modificar_empleado' e.id %}">Editar</a>
                         </td>
                         <td>
                            <a class="button alert" href="{% url 'persona_app:eliminar_empleado' e.id %}">Eliminar</a>
                         </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="cell">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                     <li class="pagination-previous">
                         <a href="?page={{page_obj.previous_page_number}}">Atras</a>
                    </li>
                    {% endif %}

                     {% for pagina in paginator.page_range %}

                     
                     {% ifequal pagina page_obj.number %} 
                     <li class="current"><span class="show-for-sr">You're on page</span> {{pagina}}</li>
                     {% else %}
                     <li class=""><a href="?page={{ pagina }}">{{ pagina }}</a></li>
                     {% endifequal %}
                     {% endfor %}

                     {% if page_obj.has_next %}
                     <li class="pagination-next">
                        <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                     </li>
                     {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div>
    </div>    
</div>
{% endblock content %}

templates/persona/success.html
<h1>felicitaciones se guardo correctamente el empleado</h1>

templates/persona/update.html
{% extends 'base.html' %}

{% block title %}
    Editar empleado
{% endblock title %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">
            Modificar empleado
        </h1>
        <div class="cell">
            <form  class="grid-x grid-margin-x" method="POST">{% csrf_token %}
                <div class="cell large-6 ">
                    <label>Nombres
                        {{ form.first_name }}
                    </label>
                </div>
                <div class="cell large-6 ">
                    <label>Apellidos
                        {{ form.last_name }}
                    </label>
                </div>
                <div class="cell large-6 ">
                    <label>Trabajo
                        {{ form.job }}
                    </label>
                </div>
                <div class="cell large-6 ">
                    <label>Area
                        {{ form.departamento }}
                    </label>
                </div>
                <div class="cell large-12 ">
                    <label>Habilidades extra:
                        {{ form.Habilidades }}
                    </label>
                </div>
                <div class="cell">
                    <button type="submit" class="success button">Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content%}