applications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "departamento_app"

urlpatterns = [
    path('departamento-lista', views.DepartamentoListView.as_view(), name='departamento_list'),
    path('new-departamento', views.NewDepartamentoView.as_view(), name='nuevo_departamento'),
]

applications/persona/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "persona_app"

urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'),
    path('listar-todo-empleados', views.ListAllEmpleados.as_view(), name='empleados_all'),
    path('listar-empleados-admin', views.ListaEmpleadosAdmin.as_view(), name='empleados_admin'),
    path('lista-by-area/<shorname>/', views.ListByAreaEmpleado.as_view(), name='empleados_area'),
    path('buscar-empleado', views.ListEmpleadosByKword.as_view()),
    path('listar-habilidades-empleado', views.ListHabilidadesHempleados.as_view()),
    path('ver-empleado/<pk>/', views.EmpleadoDetailView.as_view(), name='Empleado_Detail'),
    path('add-empleado', views.EmpleadoCreateView.as_view(), name='empleado_add'),
    path('success', views.SuccessView.as_view(), name='correcto'),
    path('update-empleado/<pk>/', views.EmpleadoUpDateView.as_view(), name='modificar_empleado'),
    path('delete-empleado/<pk>/', views.EmpleadoDeleteView.as_view(), name='eliminar_empleado'),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.departamento.urls')),
    re_path('', include('applications.persona.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.persona.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departamento/models.py
from enum import unique
from tabnanny import verbose
from django.db import models

# para saber que tipo de model usar para cada tipo de datos a solicitar buscar en google :
# "django models fields type"(en la pag de documentacion de django)
class Departamento(models.Model):
    name = models.CharField('Nombre', max_length=50,)
    shor_name = models.CharField('Nombre Corto', max_length=20, unique=True)
    anulate = models.BooleanField('anulado', default=False)

    class Meta:
        verbose_name = 'Mi Departamentos'
        verbose_name_plural = 'Areas de la Empresa'
        ordering = ['-name']
        unique_together = ('name', 'shor_name')
            
    def __str__(self):
        return str(self.id) + '-' + self.name + '-' + self.shor_name

applications/departamento/forms.py
from django import forms

class NewDepartamentoForm(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellidos = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    shor_name = forms.CharField(max_length=20)

applications/departamento/views.py
from ast import For
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic.edit import FormView
from applications.persona.models import Empleado
from .models import Departamento
from .forms import NewDepartamentoForm



class DepartamentoListView(ListView):
    template_name = "departamento/lista.html"
    model = Departamento
    context_object_name = 'departamentos'




class NewDepartamentoView(FormView):
    template_name = 'departamento/new_deparamento.html'
    form_class = NewDepartamentoForm
    success_url = '/'
    
    def form_valid(self, form):
        print('*******estamos en el form_valid******')
        
        depa = Departamento(
            name=form.cleaned_data['departamento'],
            shor_name=form.cleaned_data['shor_name']
        )
        depa.save()
        
        nombre = form.cleaned_data['nombre']
        apellido = form.cleaned_data['apellidos']
        Empleado.objects.create(
            first_name=nombre,
            last_name=apellido,
            job='1',
            departamento=depa
        )
        return super(NewDepartamentoView, self).form_valid(form)

templates/departamento/lista.html
{% extends 'base.html' %}

{% block title %}
    Lista departamentos
{% endblock %}

{% block content %}
    {% include "includes/header.html" %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista departamentos</h1>
            <div class="cell">
                <table>
                    <tbody>
                        {% for departamentos in departamentos %}
                        <tr>
                            <td>{{ departamentos.name }}</td>
                            <td>{{ departamentos.shor_name }}</td>
                            <td>
                                <a class="button warning" href="{% url 'persona_app:empleados_area' departamentos.shor_name %}">Ver Empleados</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}

templates/departamento/new_deparamento.html
{% extends 'base.html' %}

{% block title %}
   Registrar Departamento
{% endblock title %}

{% block content %}
   
{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar Departamento</h1>
        <form class="cell callout grid-x grid-margin-x" method="POST">{% csrf_token %}
            <div class="medium-6 cell">
                <label>Nombres:
                    {{form.nombre}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Apellidos:
                    {{form.nombre}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Departamento:
                    {{form.nombre}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Shor_name:
                    {{form.nombre}}
                </label>
            </div>
            <div class="medium-12 cell">
                <button type="submit" class="button">Guardar</button>
            </div>
        </form>
    </div>
</div>

{% endblock content %}
    <button type="submit" class="button">Guardar</button>